services:
  navidrome:
    image: deluan/navidrome:latest
    restart: unless-stopped
    ports:
      - 4533:4533
    environment:
      ND_CONFIGFILE: /config/navidrome.toml
    volumes:
      - ./music:/music:ro
      - ./data:/data
      - ./navidrome.toml:/config/navidrome.toml:ro
